### ISSUE TITLE
Unicode to ANSI converter

### ISSUE THREAD

**Issue by TasmiaZerin1128** [BinduLogic/bn-ansi-to-unicode#1]
Hello there! I am working on an application in Unity, where I need to add Bangla text. The data is stored in Firebase, which I want to convert to ANSI to show with the ANSI fonts in Unity, as Unity still does not support writing in Unicode for Bangla language. I checked your code, you have made an excellent converter! Did you work on the reverse conversion for Unicode to ANSI? If you have, it would be very helpful for me.

**Comment by zedrex** [comment]
@TasmiaZerin1128 Sorry for the extremely late reply. We haven't worked with with ANSI to Unicode conversion. If you look at the codebase, there are character mappings which can be reversed to get your intended use case.

**Comment by zedrex** [comment]
Seems like you have already implemented it in C#. Kudos to you!
